### ISSUE TITLE
What's the purpose for this plugin?

### ISSUE THREAD

**Issue by BOplaid** [ninathedev/MagmanodeCore-Plugin#1]
?

**Comment by ninathedev** [comment]
I don't know; this is used by the Minecraft hosting provider Magmanode. Looking at the plugin files, it looks like it is used for the use of Magmanode API, but I might be wrong.

**Comment by BOplaid** [comment]
I opened a ticket in their discord and they told me that it's for statistics. And by statistics they mean uptime and number of players.
I thought this was the plugin that turns your server off when there are no players in it. But it turns out I was wrong.
I asked them the timer that starts whenever there are no players, and he said that it depends on how many players are in the node. It is from 5-120 minutes if I remember correctly. after that timer runs out, the server shuts off.
But again, the timer thing is not associated with this plugin. I just said it in case you wanted to know.
